export const SET_IS_INPUT_VISIBLE = 'SET_IS_INPUT_VISIBLE';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const SUBMIT_INPUT = 'SUBMIT_INPUT';
export const SET_INPUT_ERROR = 'SET_INPUT_ERROR';